baseURL: https://628aa11a251d530008d34cc3--silver-sawine-8e3e6d.netlify.app/
disableKinds:
  - section
  - taxonomy
  - term
  - RSS
  - robotsTXT
defaultContentLanguage: en
theme: hugo-scroll
title: Meenser Landhonig
params:
  copyright: © Sebastian Streit
  description: Imker
  favicon: images/favicon.ico
  images: images/cover-image.png
  meta:
    keywords: Honig, Bienen, Imkerei, Meensen
  title: Meenser Landhonig
